Issue #16
technojam/Mind-Optimizers pull request #22
Opened 2021-10-03 20:51 UTC by fernandadagostin

Fixing the horizontal scrollbar and making title images responsive.

2021-10-04 17:37 UTC, aashimawadhwa requested changes
changing the image size won't really help because every system have different ratio the website will not be responsive . try searching for different properties of CSS that will help .

2021-10-04 18:08 UTC, fernandadagostin commented
Please, consider that there are more changes them the image size.  All @media are planned to produce a good responsive result.

Here is an example of the page result.
![ezgif com-gif-maker](https://user-images.githubusercontent.com/33377159/135901681-39b72f73-b192-4174-a0b0-4e4d64931378.gif)


about the image size, let me kwon if that is a requirement and I can update the code to meet that.

2021-10-06 07:47 UTC, aashimawadhwa approved these changes

2021-10-06 07:47 UTC, merged

2021-10-09 23:05 UTC, fernandadagostin commented
For your information, it is not counting for Hacktoberfest 2021.
Thank you.